#ifndef LIBPOCSAG_VERSION_H
#define LIBPOCSAG_VERSION_H

#define LIBPOCSAG_VERSION_MAJOR 1
#define LIBPOCSAG_VERSION_MINOR 0
#define LIBPOCSAG_VERSION_PATCH 2
#define LIBPOCSAG_VERSION_STRING "1.0.2"

#endif
